{"time":"2025-10-21T10:50:52.2378492-04:00","level":"INFO","msg":"stream: starting","core version":"0.22.2"}
{"time":"2025-10-21T10:50:53.1230849-04:00","level":"INFO","msg":"stream: created new stream","id":"3dxm0so3"}
{"time":"2025-10-21T10:50:53.12362-04:00","level":"INFO","msg":"handler: started","stream_id":"3dxm0so3"}
{"time":"2025-10-21T10:50:53.1410674-04:00","level":"INFO","msg":"stream: started","id":"3dxm0so3"}
{"time":"2025-10-21T10:50:53.1410674-04:00","level":"INFO","msg":"writer: started","stream_id":"3dxm0so3"}
{"time":"2025-10-21T10:50:53.1417573-04:00","level":"INFO","msg":"sender: started","stream_id":"3dxm0so3"}
{"time":"2025-10-21T17:49:59.4444149-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T17:50:22.658098-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:28:39.6054415-04:00","level":"INFO","msg":"flowcontrol: backed up, offloading to disk","recordNumber":70051}
{"time":"2025-10-21T18:28:56.6013661-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-10-21T18:28:58.7402678-04:00","level":"INFO","msg":"flowcontrol: unblocked","totalOffloaded":55}
{"time":"2025-10-21T18:29:34.7793323-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:29:57.9452001-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:30:23.1967941-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:30:56.7798154-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:31:19.8133763-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-21T18:31:45.7177364-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/3dxm0so3/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
